export interface ImageMetadata {
  filename: string;
  title: string;
  monthYear: string;
  description: string;
  orientation: "portrait" | "landscape" | "square";
}

export const imageGallery: ImageMetadata[] = [
  {
    filename: "DSC04541.avif",
    title: "Project Milestone Alpha",
    monthYear: "January 2026",
    description: "Initial capture of the project site under morning light.",
    orientation: "portrait",
  },
  {
    filename: "DSC04542.avif",
    title: "Structural Detail View",
    monthYear: "January 2026",
    description: "Close-up shot focusing on the primary support framework.",
    orientation: "portrait",
  },
  {
    filename: "DSC04736.avif",
    title: "Interior Progression",
    monthYear: "January 2026",
    description: "Status update on the interior layout and partition walls.",
    orientation: "portrait",
  },
  {
    filename: "DSC04861.avif",
    title: "External Facade - North",
    monthYear: "January 2026",
    description:
      "View of the north-facing facade showing material installation.",
    orientation: "portrait",
  },
  {
    filename: "DSC04875.avif",
    title: "Landscape Integration",
    monthYear: "January 2026",
    description: "Review of the surrounding landscape and drainage paths.",
    orientation: "portrait",
  },
  {
    filename: "DSC04884.avif",
    title: "Material Samples",
    monthYear: "January 2026",
    description: "Documentation of approved exterior finishes.",
    orientation: "portrait",
  },
  {
    filename: "DSC04985.avif",
    title: "Utility Connection Point",
    monthYear: "January 2026",
    description: "Detailed view of the main electrical and water entry points.",
    orientation: "portrait",
  },
  {
    filename: "DSC05005-2.avif",
    title: "Roof Line Profile",
    monthYear: "January 2026",
    description: "Elevation view of the secondary roof structure.",
    orientation: "portrait",
  },
  {
    filename: "DSC05013.avif",
    title: "Upper Deck Overview",
    monthYear: "January 2026",
    description: "Wide angle of the upper floor assembly.",
    orientation: "landscape",
  },
  {
    filename: "DSC05015.avif",
    title: "Stairwell Framework",
    monthYear: "January 2026",
    description: "Internal structural check for the central staircase.",
    orientation: "portrait",
  },
  {
    filename: "DSC05026-2.avif",
    title: "South Entrance Detail",
    monthYear: "January 2026",
    description: "Main entryway progress showing frame installation.",
    orientation: "portrait",
  },
  {
    filename: "DSC05042.avif",
    title: "Window Framing Phase 1",
    monthYear: "January 2026",
    description: "Installation of thermal-broken window frames.",
    orientation: "portrait",
  },
  {
    filename: "DSC05055.avif",
    title: "Floor Insulation Check",
    monthYear: "January 2026",
    description: "Verification of sub-floor insulation layers.",
    orientation: "portrait",
  },
  {
    filename: "DSC05089.avif",
    title: "HVAC Ductwork Path",
    monthYear: "January 2026",
    description: "Mapping of internal ventilation systems.",
    orientation: "portrait",
  },
  {
    filename: "DSC05092.avif",
    title: "Electrical Grid Layout",
    monthYear: "January 2026",
    description: "Visible wiring paths before drywall installation.",
    orientation: "portrait",
  },
  {
    filename: "DSC05105.avif",
    title: "Plumbing Pressure Test",
    monthYear: "January 2026",
    description: "Monitoring pressure gauges for the internal water system.",
    orientation: "portrait",
  },
  {
    filename: "DSC05153.avif",
    title: "Drywall Installation - Unit A",
    monthYear: "January 2026",
    description: "First layer of gypsum board application.",
    orientation: "portrait",
  },
  {
    filename: "DSC05154.avif",
    title: "Joint Taping Process",
    monthYear: "January 2026",
    description: "Finishing work on the interior wall seams.",
    orientation: "portrait",
  },
  {
    filename: "DSC05158.avif",
    title: "Ceiling Support Grid",
    monthYear: "January 2026",
    description: "Suspended ceiling track installation.",
    orientation: "portrait",
  },
  {
    filename: "DSC05188.avif",
    title: "Flooring Underlayment",
    monthYear: "January 2026",
    description: "Soundproofing layer applied across the main level.",
    orientation: "portrait",
  },
  {
    filename: "DSC06144.avif",
    title: "Lighting Fixture Mockup",
    monthYear: "January 2026",
    description: "Testing of recessed LED lighting units.",
    orientation: "portrait",
  },
  {
    filename: "DSC06195.avif",
    title: "Cabinetry Installation",
    monthYear: "January 2026",
    description: "Fitting of the custom kitchen millwork.",
    orientation: "landscape",
  },
  {
    filename: "DSC06259.avif",
    title: "Countertop Placement",
    monthYear: "January 2026",
    description: "Installation of quartz surfaces in the kitchen.",
    orientation: "landscape",
  },
  {
    filename: "DSC06362.avif",
    title: "Bathroom Tiling Detail",
    monthYear: "January 2026",
    description: "Close-up of the ceramic tile pattern in the master bath.",
    orientation: "portrait",
  },
  {
    filename: "DSC06395.avif",
    title: "Hardware Finish Check",
    monthYear: "January 2026",
    description: "Review of door handles and hinges in matte black.",
    orientation: "landscape",
  },
  {
    filename: "DSC06439.avif",
    title: "Exterior Siding Completion",
    monthYear: "January 2026",
    description: "Final check of the cedar cladding installation.",
    orientation: "landscape",
  },
  {
    filename: "DSC06446.avif",
    title: "Outdoor Patio Slab",
    monthYear: "January 2026",
    description: "Poured concrete patio curing process.",
    orientation: "landscape",
  },
  {
    filename: "DSC06453.avif",
    title: "Retaining Wall Build",
    monthYear: "January 2026",
    description: "Masonry work on the site elevation transitions.",
    orientation: "landscape",
  },
  {
    filename: "DSC06454.avif",
    title: "Drainage Grate Install",
    monthYear: "January 2026",
    description: "Installation of heavy-duty exterior drainage.",
    orientation: "landscape",
  },
  {
    filename: "DSC06489.avif",
    title: "Balcony Railing Assembly",
    monthYear: "January 2026",
    description: "Glass and steel railing installation for safety.",
    orientation: "landscape",
  },
  {
    filename: "DSC06685.avif",
    title: "Paint Selection Review",
    monthYear: "January 2026",
    description: "Final walkthrough of the neutral wall tones.",
    orientation: "portrait",
  },
  {
    filename: "DSC06839.avif",
    title: "HVAC External Unit",
    monthYear: "January 2026",
    description: "Placement of the heat pump units on the exterior pad.",
    orientation: "landscape",
  },
  {
    filename: "DSC06850.avif",
    title: "Smart Home Hub Setup",
    monthYear: "January 2026",
    description: "Central control panel configuration.",
    orientation: "landscape",
  },
  {
    filename: "DSC06854.avif",
    title: "Fiber Optic Entry",
    monthYear: "January 2026",
    description: "High-speed data line termination point.",
    orientation: "landscape",
  },
  {
    filename: "DSC06865.avif",
    title: "Solar Panel Array",
    monthYear: "January 2026",
    description: "Rooftop view of the photovoltaic installation.",
    orientation: "portrait",
  },
  {
    filename: "DSC06877.avif",
    title: "Inverter Station",
    monthYear: "January 2026",
    description: "Electrical setup for the solar energy conversion.",
    orientation: "portrait",
  },
  {
    filename: "DSC06928.avif",
    title: "Garage Door Mechanism",
    monthYear: "January 2026",
    description: "Testing of the insulated sectional door.",
    orientation: "portrait",
  },
  {
    filename: "DSC07020.avif",
    title: "Final Site Clean-up",
    monthYear: "January 2026",
    description: "Removal of debris and preparation for handover.",
    orientation: "portrait",
  },
  {
    filename: "DSC07049.avif",
    title: "Driveway Paving",
    monthYear: "January 2026",
    description: "Asphalt application for the main approach.",
    orientation: "portrait",
  },
  {
    filename: "DSC07126.avif",
    title: "Landscaping - Planting",
    monthYear: "January 2026",
    description: "Installation of native shrubs and trees.",
    orientation: "landscape",
  },
  {
    filename: "DSC07155.avif",
    title: "Exterior Lighting Night Test",
    monthYear: "January 2026",
    description: "Testing of the security and ambient site lights.",
    orientation: "portrait",
  },
  {
    filename: "DSC07187.avif",
    title: "Project Final Capture",
    monthYear: "January 2026",
    description: "Wide-angle hero shot of the completed project.",
    orientation: "portrait",
  },
];
